name: reactions
version: 0.1.0.0
github: "0nkery/silver-tribble"
license: BSD3
author: "Dmitry"
maintainer: "example@example.com"
copyright: "2019 Dmitry"

extra-source-files:
  - README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: Please see the README on GitHub at <https://github.com/0nkery/silver-tribble#readme>

dependencies:
  - base >= 4.7 && < 5
  - hasbolt >= 0.1 && < 0.2

library:
  source-dirs: src

executables:
  reactions-exe:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - reactions

tests:
  reactions-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - reactions
